Penguin Avatars and No Events Fix
TheHuddle/website pull request #19
Opened 2022-01-15 17:04 UTC by sjtolley9

Added a new default avatar (src/assets/default_profile.png), and an extra placeholder (src/assets/profile.png) for legacy sake. Resolves #11
Updated `assets.service.ts` to return the default avatar if no avatar is found. Resolves #12
Fixed issue (#15) that caused the event card for "No Current Events" to display the current time as the start and end date. Checked that both dates existed before passing them to `moment` and formatting.

2022-01-16 17:54 UTC, wrynegade requested changes
I love the new asset!

Did you mean to include `profile.png`? If so, what is the use-case?

2022-01-16 17:54 UTC, wrynegade commented on src/app/services/assets.service.ts
> +      return `${environment.apiBase}/assets/default_profile.png`;
Since this is the general assets service, I would like a more general name; `default.png` I think works nicely

2022-01-16 17:54 UTC, wrynegade commented on src/app/pages/events/card/component.ts
> +	}
good catch!

2022-01-17 02:19 UTC, wrynegade commented
In the future, try to keep issues separate. Obviously I don't mind seeing #11 and #12 together, but it is much easier to keep track of #15 in a separate PR! I definitely don't mind multiple PRs! The more the merrier!

2022-01-17 17:53 UTC, wrynegade commented on src/app/pages/events/card/component.ts
> +	}
Please feel free to overwrite my quick-guard with yours.

I just needed tests to pass in order to automate deployment :)

2022-01-17 19:21 UTC, sjtolley9 commented
Changes have been made, and pre-push checks are now passing. Default asset will not be available until merged with main as it is dependent on the asset being in `environment.apiBase`.

2022-01-17 19:39 UTC, wrynegade approved these changes
Looks great and works great! Excellent job :+1:

2022-01-17 19:41 UTC, merged